name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - develop
      - feature/orderbook

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    container: 
      image: docker.io/kentsday/dfx_rust:bullseye
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set pipenv
        run: |
          cd $GITHUB_WORKSPACE/src
          pipenv install

      - name:  unit test
        run: |
          cd $GITHUB_WORKSPACE/src
          cargo test

      - name: canister start
        run: |
          cd $GITHUB_WORKSPACE/src
          dfx start --host 0.0.0.0:8000 --background
          pipenv run invoke deploy
          pipenv run invoke test
          dfx stop