name: build Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  
jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/kentsday/dfx_rust:bullseye-dfx-0.10.1-1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: src/package-lock.json
      - run: |
          cd src
          ./start.sh
          ./sh_setup_dev.sh
          ./sh_package.sh
